name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install
        
    

      - name: Run tests with coverage
        run: |
          pdm run pytest --cov=src --cov-report=xml --cov-report=term
          pip install coverage-badge
          coverage-badge -o coverage.svg -f

      - name: Commit and push coverage badge
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          mv coverage.svg docs/coverage.svg
          git add docs/coverage.svg
          git commit -m "Update coverage badge"
          git push
