name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install
          pip install pytest pytest-cov coverage-badge

      - name: Run lint checks (Ruff)
        run: pdm run ruff .

      - name: Check formatting (Black)
        run: pdm run black --check .

      - name: Run tests with coverage
        run: |
          pdm run pytest --cov=src --cov-report=xml --cov-report=term-missing
          coverage-badge -o coverage.svg -f

      - name: Upload coverage badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage.svg
